name: Push workflow dispatch

on:
  push:
    paths:
      - '**/*.yml'
      - '**/*.py'
    branches: main

jobs:
  checks:
    runs-on: ubuntu-latest

    if: |
      github.event_name == 'push' &&
      github.repository == 'illusion0001/console-game-patches'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup dependencies
        run: pip install -r requirements.txt

      - name: Pack zip
        run: |
          mkdir -p output/yml
          python file-autogen.py
          current=$(date '+%Y-%m-%d %H:%M:%S %A (%Z %z)')
          msg="Patch database version: $current"
          msg_md="Patch archive built on: \`$current\`"
          echo $msg > output/build.txt
          echo $msg > build.txt
          echo $msg_md > patch_built.md
          mv output patches
          zip -r patch1.zip patches/*
          mkdir out
          cp patch1.zip CNAME build.txt patch_built.md .github/README.md out/

      - name: Deploy
        run: |
          cd out
          git init
          git add -A
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m 'Deploy patch asset'

      - name: Force push to destination branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
          directory: out

      - name: Checkout website
        uses: actions/checkout@v3
        with:
          repository: illusion0001/illusion0001.github.io

      - name: Run Website Workflow dispatch
        env:
          GITHUB_TOKEN: ${{ secrets.website }}
        run: gh workflow run jekyll.yml
